source:
  indeed:
      job:
        search: "http://api.indeed.com/ads/apisearch?"
        info: "https://www.indeed.com/viewjob?"
      auth: {"publisher": ""} # Enter Indeed API Publisher Key
  careerbuilder:
      base: "http://api.careerbuilder.com/"
      job:
        codes:
            categorycodes: "http://api.careerbuilder.com/v2/categories?"
            educationcodes: "http://api.careerbuilder.com/v2/educationcodes?"
            employmenttypes: "http://api.careerbuilder.com/v2/employeetypes?"
            industrycodes: "http://api.careerbuilder.com/v2/industrycodes?"
        search: "http://api.careerbuilder.com/v2/jobsearch?"
        info: "http://api.careerbuilder.com/v3/job?"
        recommend: "http://api.careerbuilder.com/v2/recommendations/forjob"
      apply:
        blank: "http://api.careerbuilder.com/v2/application/blank"
        submit: "http://api.careerbuilder.com/v2/application/submit"
        form: "http://api.careerbuilder.com/v2/application/form"
        link: "http://api.careerbuilder.com/v2/application/applylink"
      company:
        recommend: "http://api.careerbulder.com/employer/jobrecommendation"
      auth: {"DeveloperKey": ""} # Enter Careerbuilder API Developer Key
  glassdoor:
      base: "http://api.glassdoor.com/api/api.htm?"
      job:
        search: "https://www.glassdoor.com/Job/jobs.htm?"
        info: "Detail url for glassdoor queries must be autogenerated during search"
        stats: "http://api.glassdoor.com/api/api.htm?action=jobs-stats"
        prog:  "http://api.glassdoor.com/api/api.htm?action=jobs-prog"
      company:
        list: "http://api.glassdoor.com/api/api.htm?action=employers"
      auth: {"t.p": "", "t.k": ""} # Enter Glassdoor API Password & Key
  muse:
      base: "https://api-v2.themuse.com/"
      job:
        search: "https://api-v2.themuse.com/jobs?"
        info: "https://api-v2.themuse.com/jobs/"
      company:
        list: "https://api-v2.themuse.com/companies?"
        info: "https://api-v2.themuse.com/companies/"
      auth: {"api_key":""} # Enter The Muse API Key
common:
  request:
    headers: {"user-agent":"Mozilla/5.0 (X11; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0", "connection":"keep-alive"}


